language: go
go:
- '1.10'
sudo: false
install:
- go get -v github.com/alecthomas/gometalinter
- gometalinter --install
script:
  #- go get  ./...
  - chmod +x ./goclean.sh
  - ./goclean.sh
  - cd ./cmd/photonmonitoring
  - go build
  - pwd

notifications:
  email:
    on_success: never
    on_failure: always
